### ISSUE TITLE
Size of capacitors 0805 for 10µF

### ISSUE THREAD

**Issue by codetiger** [technoblogy/minimal-rp2040-board#1]
Hi, 
Thanks for the wonderful work. I've been using this a reference for my work on RP2040 based PCB. I am new to SMD and electronics. 
For 10µF alone you have used 0805 and for all others you have used 0402. Is there anything I need to understand in basic SMD electronic part size for choosing.?

**Comment by technoblogy** [comment]
I usually use 0805 resistors and capacitors because they're easier to work with, and have a stock of them, but for the RP2040 board I decided that I wouldn't be able to fit them in, and so ordered some 0402 ones for the tight situations. I think it might not be possible to get 10µF in 0402 size because they can't be made that small, but otherwise either size would be equally suitable.

**Comment by codetiger** [comment]
Thanks for the info. Am Just learning SMT, my soldering skills are not that great, so probably going to use an PCBA service for the first time.
